FROM ubuntu:24.04

# RUN apt-get update && apt-get install -y \
#     python

WORKDIR /home
# RUN git config --global --add safe.directory '*' \
#     && git config --global user.email "anon@example.com" \
#     && git config --global user.name "anon" \
#     && git config --global init.defaultBranch main