#!/bin/bash

SOLETTA_URL=https://github.com/solettaproject/soletta
SOLETTA_BASE_OS=linux # for simplicity we assume Linux here, other options: https://github.com/solettaproject/soletta/tree/master/tools/build

# Soletta vendors Linux Kconfig in tools/kconfig. Its README.kconfig states
# that this copy is from Linux v4.0-rc1 and should be kept as-is.
#
# The top-level Kconfig is not self-contained: it sources Kconfig.gen, which is
# generated by data/scripts/dependency-resolver.py from dependency probes, and
# then selects the platform fragment through source "tools/build/Kconfig.$BASE_OS".
define-system \
    --system soletta \
    --kconfig-file Kconfig \
    --lkc-directory tools/kconfig \
    --environment BASE_OS=$SOLETTA_BASE_OS,PREFIX=/usr,CFLAGS=-w,LDFLAGS=-L/usr/lib,BOARD_NAME=unknown \
    --sample-branch master

add-soletta-system() {
    add-hook-step configfix-pre-extraction-hook configfix-pre-extraction-hook-soletta
    add-system --system soletta --url "$SOLETTA_URL"
}

add-soletta-kconfig-tags(from=, to=) {
    add-soletta-kconfig-revisions "$(git-tags soletta | start-at-revision "$from" | stop-at-revision "$to")"
}