#!/bin/bash

TIZENRT_URL=https://github.com/Samsung/TizenRT.git
define-system \
    --system tizenrt \
    --sample-branch master

add-tizenrt-system() {
    add-hook-step kconfig-post-checkout-hook kconfig-post-checkout-hook-tizenrt
    add-system --system tizenrt --url "$TIZENRT_URL"
    add-linux-system
}

# use Linux 4.11 LKC as kconfig-frontends-compatible parser
add-tizenrt-kconfig(revision, lkc_revision=v4.11) {
    add-tizenrt-system
    if [[ ! -d $(input-directory)/tizenrt ]]; then
        return
    fi

    add-linux-lkc-binding --revision "$lkc_revision"
    add-revision --system tizenrt --revision "$revision"
    # CONFIGSDIR is needed by the oldest TinyAra tags
    add-kconfig-model \
        --system tizenrt \
        --revision "$revision" \
        --kconfig-file os/Kconfig \
        --lkc-directory "$(none)" \
        --lkc-binding-file "$(linux-lkc-binding-file "$lkc_revision")" \
        --environment APPSDIR=apps,CONFIGSDIR=build/configs,EXTERNALDIR=external,LIBDIR=lib,LOADABLEDIR=loadable_apps,srctree=.
}

add-tizenrt-kconfig-tags(from=, to=) {
    add-tizenrt-kconfig-revisions --revisions "$(git-tags tizenrt | start-at-revision "$from" | stop-at-revision "$to")"
}

kconfig-post-checkout-hook-tizenrt(system, revision) {
    if [[ $system == tizenrt ]]; then
        generate-tizenrt-kconfig-aggregators
        patch-tizenrt-kconfig-source-paths
    fi
}

generate-tizenrt-kconfig-aggregators() {
    write-tizenrt-kconfig-aggregator apps/Kconfig apps Kconfig
    write-tizenrt-kconfig-aggregator apps/Kconfig_ENTRY apps 'Kconfig_ENTRY|Kconfig_entry'
    write-tizenrt-kconfig-aggregator loadable_apps/Kconfig loadable_apps Kconfig
}

write-tizenrt-kconfig-aggregator(output_file, directory, file_pattern) {
    [[ -d $directory ]] || return 0
    mkdir -p "$(dirname "$output_file")"
    {
        echo '# This file is generated by torte.'
        find "$directory" -mindepth 2 -type f \
            | grep -E "/($file_pattern)$" \
            | grep -Fvx "$output_file" \
            | sort \
            | sed 's#.*#source "&"#'
    } > "$output_file"
}

patch-tizenrt-kconfig-source-paths() {
    # mimic running kconfig from os/ while torte extracts from the repository root
    local path
    for path in os/*; do
        [[ -e $path ]] || continue
        [[ -e ${path#os/} ]] && continue
        ln -s "$path" "${path#os/}"
    done

    # current TizenRT carries generated-style absolute paths in a few Kconfigs
    find . -name 'Kconfig*' -type f -exec sed -i \
        -e 's#"/root/tizenrt/#"#g' \
        -e 's#"\.\./framework/#"framework/#g' \
        -e 's#source[[:space:]]\+\.\./framework/#source framework/#g' \
        -e 's#"\$FRAMEWORK_DIR/#"framework/#g' \
        {} +
    wrap-source-statements-in-double-quotes -name 'Kconfig*'
}
